apiVersion: apps/v1
kind: Deployment
metadata:
  name: bms-app
  labels:
    app: bookmyshow
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bookmyshow
  template:
    metadata:
      labels:
        app: bookmyshow
    spec:
      containers:
      - name: bms-container
        image: vaaisshnnu/bookmyshow:latest  # Replace with your Docker image
        ports:
        - containerPort: 3000  # Replace with the port your app runs on
