apiVersion: v1
kind: Service
metadata:
  name: bms-service
spec:
  type: LoadBalancer   # ← THIS exposes to internet via cloud LB (like ELB on AWS)
  selector:
    app: bookmyshow
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
